name: Android build & upload to Google Play Store
on:
  # Run on pull request merge
  push:
    branches:
      - production

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: